project:
  type: website

website:
  title: "Atiq Ur Rehman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Education.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



