---
title: "🎓 Education"
toc: false
---

## 🎓 Education

### Master of Statistics  
**Australian National University, Canberra, Australia**  
*Feb 2023 – Nov 2024*  
Projects:  
- Analysed Australian workforce survey data using **R**, **R Markdown**, and **Power BI** to identify key factors influencing remote vs office work preferences, including industry, household composition, and organisational support.  
- Performed time series forecasting of **Canberra’s monthly temperatures** and **global temperature anomalies** using R and R Markdown.

### MPhil in Statistics  
**International Islamic University, Islamabad, Pakistan**  
*Sep 2018 – May 2021*  
Thesis:  
- Investigated the interrelationship between **global warming**, **climate change**, and **air pollution** using **Vector Auto-Regressive (VAR)** and **Generalised Additive Models (GAMs)**.  
- Compared the performance of **Random Forest algorithms** implemented in two different R packages.

### Bachelor of Science (BS) in Statistics  
**University of Peshawar, Peshawar, Pakistan**  
*2013 – 2017*  
Thesis:  
- **High-dimensional covariance matrix regularisation** using more informative target matrices.
